### ISSUE TITLE
Is 1.0.0 the appropriate release to use with Nomad 1.2.0

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/nomad-device-nvidia#4]
I'm getting ready to upgrade a cluster where several nodes use the nvidia driver.  It looks like this repo has precious few release(s) and I'm wondering if the only one currently up is the release to use with 1.2.0.

**Comment by tgross** [comment]
Hi @the-maldridge! 1.0 should be the right release to use for 1.2.0.

In general, the device driver interface has been very stable since we built it, so I wouldn't expect changes in Nomad to impact this driver much at all. That's one of the reasons why we considered it safe to externalize the driver.
